# -*- coding: utf-8 -*-
"""streamlit_app_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfVvRF_Cr7V0vWzSfdOGAuQOxLtOdBvn?resourcekey=0-dI_21uJw6_wVj-0_fuEf6A
"""

import streamlit as st

# Streamlitアプリのタイトルを設定
st.title("Placeholder for toppage")

st.markdown('---')
st.markdown('description')
st.markdown('---')